{
 "title": "SmartConx-ENV-Logs",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "Service_Name",
    "label": "Service_Name",
    "query": {}
   },
   {
    "name": "PodName",
    "label": "PodName",
    "query": {}
   },
   { "name": "string", "label": "Log_String" },
   { "name": "FrontDoorRequestURIString", "label": "FrontDoorRequestURIString" }
  ]
 },
 "panels": [
  {
   "title": "Front Door Logs",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where ResourceProvider == \"FRONTDOOR_RESOURCE_PROVIDER\" and Category == \"FRONTDOOR_CATEGORY\"\r\n| where TimeGenerated between (datetime(${__from:date:iso}) .. datetime(${__to:date:iso}))\r\n| where requestUri_s !contains \"/grafana\"\r\n| where requestUri_s has_any (\"${FrontDoorRequestURIString}\")\r\n| project REQUEST_URL=requestUri_s, LOCAL_TIME=TimeGenerated  ,STATUS_CODE=httpStatusCode_d, HTTP_METHOD=httpMethod_s, CLIENT_IP=clientIp_s, SOCKET_IP=socketIp_s, SECURITY_PROTOCOL=securityProtocol_s, USER_AGENT=userAgent_s",
      "resources": [
       "LOG_ANALYTICS_WORKSPACE_RESOURCE_ID"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Front Door Request Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where ResourceProvider == \"FRONTDOOR_RESOURCE_PROVIDER\" and Category == \"FRONTDOOR_CATEGORY\"\r\n| where TimeGenerated between (datetime(${__from:date:iso}) .. datetime(${__to:date:iso}))\r\n| where requestUri_s !contains \"/grafana\"\r\n| where requestUri_s has_any (\"${FrontDoorRequestURIString}\")\r\n| summarize count = tostring(count())",
      "resources": [
       "LOG_ANALYTICS_WORKSPACE_RESOURCE_ID"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Total Log Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({namespace=\"$Namespace\", app=~\"$Service_Name\", pod=~\"$PodName\"} |~ `(?i)$string`[$__range])"
    }
   ]
  },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 115, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=\"$Namespace\", app=~\"$Service_Name\", pod=~\"$PodName\"} |~ `$string`"
    }
   ]
  }
 ]
}