{
 "title": "MONGODB-Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MongoDB Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mongodb_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MongoDB Up Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "mongodb_ss_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MongoDB current Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Performing Active Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Total Created Connections Since server started",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"totalCreated\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Available Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"available\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Delete Operation occured",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"delete\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB query Operation occured",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"query\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Insert Operation occured",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"insert\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Updated Operation occured",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"update\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB command excute in data base",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"command\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB get More Operation data base",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"getmore\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Collections/DB",
   "type": "state-timeline",
   "description": "Number of collections in the database.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "targets": [
    { "expr": "mongodb_dbstats_collections", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "Total Indexs/DB",
   "type": "state-timeline",
   "description": "Number of collections in the database.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "targets": [
    { "expr": "mongodb_dbstats_indexes", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "Total Views/DB",
   "type": "state-timeline",
   "description": "Number of collections in the database.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "targets": [
    { "expr": "mongodb_dbstats_views", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "Allocated Storage to Collections in DB",
   "type": "timeseries",
   "description": "Sum of the space allocated to all collections in the database for document storage, including free space.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mongodb_dbstats_storageSize", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "Allocated Storage to Indexs in DB",
   "type": "timeseries",
   "description": "Sum of the space allocated to all indexes in the database, including free index space.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    { "expr": "mongodb_dbstats_indexSize", "legendFormat": "{{database}}" }
   ]
  },
  {
   "title": "CPU Usage for MongoDB Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"syndication\", pod=\"mongodb-0\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"syndication\", pod=\"mongodb-0\"}[5m])) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " MongoDB Pod Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"syndication\",persistentvolumeclaim=\"mongo-claim-mongodb-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " MongoDB Disk Total Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"syndication\",persistentvolumeclaim=\"mongo-claim-mongodb-0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}